spring.application.name=discoveryserver
server.port=8761

#bch maysajlch rouhoou eli howa MS
eureka.client.register-with-eureka=false

#ne recupere pas autre annuaire ki yabdew andna deux projets MS et deux annuaire
# nutilise pas les MS d'un autre annuaire, esstaamel mteek khw les MS mteek khw
eureka.client.fetch-registry=false